{% set name = "baal" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/baal-{{ version }}.tar.gz
  sha256: f196fc92a440385390976920388bd5137bd22adfcb1e5558a69bdc61ec685616

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4
    - pip
    - poetry
  run:
    - python >=3.7
    - pip
    - pytorch >=1.6.0
    - torchmetrics >=0.9.3
    - h5py >=3.4.0
    - numpy >=1.21.2
    - matplotlib-base >=3.4.3
    - pillow >=6.2.0
    - tqdm >=4.62.2
    - structlog >=21.1.0
    - scikit-learn >=1.0.0
    - scipy >=1.7.1

test:
  imports:
    - baal
    - baal.active

about:
  home: https://github.com/baal-org/baal
  summary: Library for bayesian active learning.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
