{% set name = "baal" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/baal-{{ version }}.tar.gz
  sha256: 61628674b45d2c368e1797a97273af0f7bfc2d629b68b8e44a9a1f24f1b116de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - pytorch >=1.6.0
    - h5py >=3.4.0
    - numpy >=1.21.2
    - matplotlib >=3.4.3
    - pillow >=6.2.0
    - tqdm >=4.62.2
    - pytorch-lightning >=1.4.0
    - structlog >=21.1.0
    - scikit-learn >=0.24.2
    - scipy >=1.7.1

test:
  imports:
    - baal
    - baal.active

about:
  home: https://github.com/ElementAI/baal
  summary: Library for bayesian active learning.
  license: Apache-2.0
  # Ticket for include the license file: https://github.com/ElementAI/baal/issues/99
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
