{% set name = "baal" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/baal-{{ version }}.tar.gz
  sha256: 6ed1a0e11e1e25dcae2b5acaa29a865613f8faf237f7e0e171fd94d0831bc247

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.10
    - pip
    - poetry
  run:
    - python >=3.7
    - pip
    - pytorch >=1.6.0
    - h5py >=3.4.0
    - numpy >=1.21.2
    - matplotlib-base >=3.4.3
    - pillow >=6.2.0
    - tqdm >=4.62.2
    - structlog >=21.1.0
    - scikit-learn >=1.0.0
    - scipy >=1.7.1

test:
  imports:
    - baal
    - baal.active

about:
  home: https://github.com/ElementAI/baal
  summary: Library for bayesian active learning.
  license: Apache-2.0
  # Ticket for include the license file: https://github.com/ElementAI/baal/issues/99
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
